### ISSUE TITLE
Support and document pushing to AWS ECR

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/repo2docker-action#65]
### Description

I want to automatically build and push images to a repository that uses [docker credential stores](https://docs.docker.com/engine/reference/commandline/login/#credential-helpers) rather than username / password to log in. This is not a documented use-case of this repository, so it's unclear whether it is supported or not.

To start off, let's try getting this action to work with [Amazon ECR](https://aws.amazon.com/ecr/), as this is a very common registry to use as a test case.

### Benefit

This would be valuable because many container registries don't user U/P credentialing (like AWS ECR). Documenting this process for one of them would make it easier for others to understand how they could apply it to other registries.

### Implementation

We could test this out by following the Amazon ECR action here:

https://github.com/aws-actions/amazon-ecr-login#usage

### Tasks

- [x] Make it possible to push to registries without requiring Username/Password (#70)
- [x] Test this process pushing to Amazon ECR and see if it works (working [example config](https://github.com/GeorgianaElena/test-repo2docker-action/blob/main/.github/workflows/build.yaml))
- [ ] Document how to get it working with Amazon ECR in the README [somewhere around here](https://github.com/jupyterhub/repo2docker-action#push-image-to-a-registry-other-than-dockerhub)

### Alternative approaches

Install repo2docker manually and push, which I've done in https://github.com/amfriesz/lpdaac_hls_tutorial/pull/2.

**Comment by choldgraf** [comment]
@yuvipanda has this been closed by https://github.com/jupyterhub/repo2docker-action/issues/70 ?

**Comment by consideRatio** [comment]
Here is an example of logging into ECR and then doing a `docker push`: https://github.com/pangeo-data/jupyter-earth/blob/8d2f1b03202158c863ff077dc04c07ec695e355f/.github/workflows/build-image.yaml#L62-L79

**Comment by GeorgianaElena** [comment]
Finally concluded that the action does indeed work with pushing to an Amazon ECR registry :tada:

I have a working example [in this repo here](https://github.com/GeorgianaElena/test-repo2docker-action/blob/main/.github/workflows/build.yaml#L12). Note that [`DOCKER_CONFIG`](https://github.com/GeorgianaElena/test-repo2docker-action/blob/dd869fcf3f902e250c134b790d9fd0510ff6c99f/.github/workflows/build.yaml#L11-L12
) needs to be set in order for `repo2docker-action` to know where to find the credentials stored in previous steps. (ref: https://github.com/docker/login-action/issues/34)

Without this, pushing the image fails with [`no basic auth credentials`](https://github.com/GeorgianaElena/test-repo2docker-action/runs/3532735848?check_suite_focus=true#step:7:288).

(thanks @sgibson91 for [pointing me](https://github.com/2i2c-org/pilot-hubs/issues/626#issuecomment-904490285) https://github.com/docker/build-push-action, this was where the quest started from)
